# Generated by Django 5.2.17 on 2026-08-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandeur',
            name='nom_complet',
        ),
        migrations.AddField(
            model_name='demandeur',
            name='carte_etudiant_date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeur',
            name='carte_etudiant_fichier',
            field=models.FileField(blank=True, null=True, upload_to='cartes_etudiants/'),
        ),
        migrations.AddField(
            model_name='demandeur',
            name='statut_verification_etudiant',
            field=models.CharField(choices=[('NON_SOUMIS', 'Non soumis'), ('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='NON_SOUMIS', max_length=32),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='delegation_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='delegation_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='nom_complet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('USAGER', 'Usager'), ('BUREAU_COURRIER', 'Bureau du Courrier'), ('AGENT_DCUVE', 'Agent DCUVE'), ('DIRECTEUR_DCUVE', 'Directeur DCUVE'), ('DIRECTEUR_CROUS_T', 'Directeur CROUS-T'), ('SERVICE_JURIDIQUE', 'Service Juridique'), ('SERVICE_COMPTABLE', 'Service Comptable'), ('SERVICE_TECHNIQUE', 'Service Technique'), ('AGENT_TERRAIN', 'Agent de Terrain'), ('AGENT_QHSE', 'Agent QHSE'), ('CELLULE_COMMUNICATION', 'Cellule Communication'), ('AMICALE', 'Amicale'), ('ADMINISTRATEUR_SI', 'Administrateur SI')], default='USAGER', max_length=32),
        ),
    ]
