# Generated by Django 5.2.17 on 2026-08-09 16:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandeur',
            name='nom_complet',
        ),
        migrations.AddField(
            model_name='demandeur',
            name='carte_etudiant_date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeur',
            name='carte_etudiant_fichier',
            field=models.FileField(blank=True, null=True, upload_to='cartes_etudiants/'),
        ),
        migrations.AddField(
            model_name='demandeur',
            name='statut_verification_etudiant',
            field=models.CharField(choices=[('NON_SOUMIS', 'Non soumis'), ('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='NON_SOUMIS', max_length=32),
        ),
        migrations.AddField(
            model_name='demandeur',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandeurs_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='delegation_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='delegation_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='nom_complet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('USAGER', 'Usager'), ('BUREAU_COURRIER', 'Bureau du Courrier'), ('AGENT_DCUVE', 'Agent DCUVE'), ('DIRECTEUR_DCUVE', 'Directeur DCUVE'), ('DIRECTEUR_CROUS_T', 'Directeur CROUS-T'), ('SERVICE_JURIDIQUE', 'Service Juridique'), ('SERVICE_COMPTABLE', 'Service Comptable'), ('SERVICE_TECHNIQUE', 'Service Technique'), ('AGENT_TERRAIN', 'Agent de Terrain'), ('AGENT_QHSE', 'Agent QHSE'), ('CELLULE_COMMUNICATION', 'Cellule Communication'), ('AMICALE', 'Amicale'), ('ADMINISTRATEUR_SI', 'Administrateur SI')], default='USAGER', max_length=32),
        ),
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=255)),
                ('cible', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
    ]
