# Generated by Django 4.2.30 on 2026-08-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_remove_demandeur_nom_complet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('USAGER', 'Usager'), ('BUREAU_COURRIER', 'Bureau du Courrier'), ('DIRECTEUR_DCUVE', 'Directeur DCUVE'), ('DIRECTEUR_CROUS_T', 'Directeur CROUS-T'), ('SERVICE_JURIDIQUE', 'Service Juridique'), ('SERVICE_COMPTABLE', 'Service Comptable'), ('SERVICE_TECHNIQUE', 'Service Technique'), ('AGENT_TERRAIN', 'Agent de Terrain'), ('AGENT_QHSE', 'Agent QHSE'), ('CELLULE_COMMUNICATION', 'Cellule Communication'), ('AMICALE', 'Amicale'), ('ADMINISTRATEUR_SI', 'Administrateur SI')], default='USAGER', max_length=32),
        ),
    ]
