# Generated by Django 4.2.30 on 2026-08-10 04:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id_local', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('localisation', models.CharField(max_length=200)),
                ('type_local', models.CharField(choices=[('RESTAURATION', 'Restauration'), ('MULTISERVICES', 'Multiservices'), ('PAPETERIE', 'Papeterie'), ('ARTISANAT', 'Artisanat'), ('AUTRE', 'Autre')], max_length=30)),
                ('zone_cartographie', models.CharField(blank=True, max_length=50)),
                ('surface_m2', models.FloatField()),
                ('capacite_accueil', models.PositiveIntegerField(default=0)),
                ('etat_physique', models.CharField(choices=[('BON_ETAT', 'Bon état'), ('NECESSITE_RENOVATION', 'Nécessite rénovation'), ('DEGRADE', 'Dégradé'), ('EN_TRAVAUX', 'En travaux')], default='BON_ETAT', max_length=30)),
                ('gestionnaire', models.CharField(choices=[('CROUS_T', 'CROUS-T'), ('AMICALE', 'Amicale')], default='CROUS_T', max_length=20)),
                ('est_libre', models.BooleanField(default=True)),
            ],
        ),
    ]
