# Generated by Django 4.2.30 on 2026-08-10 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='local',
            options={'ordering': ['-date_creation']},
        ),
        migrations.RenameField(
            model_name='local',
            old_name='id_local',
            new_name='id',
        ),
        migrations.AddField(
            model_name='local',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='local',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
