# Generated by Django 4.2.30 on 2026-08-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0002_alter_local_options_rename_id_local_local_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
