# Generated by Django 4.2.30 on 2026-08-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0004_local_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='locaux_photos/'),
        ),
    ]
