# Generated by Django 4.2.30 on 2026-08-13 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0005_local_photo'),
        ('patrimoine', '0005_photos_automatiques'),
    ]

    operations = [
    ]
