# Generated by Django 4.2.30 on 2026-08-10 18:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patrimoine', '0002_alter_local_options_rename_id_local_local_id_and_more'),
        ('contrats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comptes', '0003_alter_utilisateur_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionQHse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('type_controle', models.CharField(choices=[('SANITAIRE', 'Sanitaire'), ('TECHNIQUE', 'Technique'), ('ELECTRIQUE', 'Electrique')], max_length=50)),
                ('date_visite', models.DateTimeField()),
                ('est_conforme', models.BooleanField()),
                ('observations', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('inspecteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections_realisees', to=settings.AUTH_USER_MODEL)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='patrimoine.local')),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plainte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('TECHNIQUE', 'Technique'), ('NON_CONFORMITE_QHSE', 'Non Conformité QHSE'), ('ENVIRONNEMENT', 'Environnement'), ('DENONCIATION_ILLEGALE', 'Dénonciation Illégale')], max_length=50)),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('EN_COURS_TRAITEMENT', 'En cours de traitement'), ('RESOLUE', 'Résolue'), ('REJETEE', 'Rejetée')], default='OUVERTE', max_length=50)),
                ('urgence', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYENNE', 'Moyenne'), ('ELEVEE', 'Elevée')], default='FAIBLE', max_length=50)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('localisation_libre', models.CharField(blank=True, max_length=255)),
                ('photo_preuve', models.URLField(blank=True)),
                ('est_anonyme', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('agent_traitant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plaintes_traitees', to=settings.AUTH_USER_MODEL)),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plaintes', to='patrimoine.local')),
                ('plaignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plaintes_deposees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('niveau', models.CharField(choices=[('AVERTISSEMENT', 'Avertissement'), ('RAPPEL_A_L_ORDRE', "Rappel à l'ordre"), ('CONVOCATION', 'Convocation'), ('EXPULSION', 'Expulsion')], default='AVERTISSEMENT', max_length=50)),
                ('statut_sanction', models.CharField(choices=[('NOTIFIEE', 'Notifiée'), ('LEVEE', 'Levée')], default='NOTIFIEE', max_length=50)),
                ('date_application', models.DateTimeField(auto_now_add=True)),
                ('date_levee', models.DateTimeField(blank=True, null=True)),
                ('motif', models.TextField()),
                ('agent_prononcant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sanctions_prononcees', to=settings.AUTH_USER_MODEL)),
                ('contrat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanctions', to='contrats.contrat')),
                ('inspection_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanction_generee', to='terrain.inspectionqhse')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='patrimoine.local')),
                ('plainte_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanction_generee', to='terrain.plainte')),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AvisCantine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('note_etoiles', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('PUBLIE', 'Publié'), ('SIGNALE', 'Signalé'), ('MASQUE', 'Masqué')], default='PUBLIE', max_length=50)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_rediges', to='comptes.demandeur')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='patrimoine.local')),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
    ]
