# Generated by Django 4.2.30 on 2026-08-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plainte',
            name='date_limite_sla',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionqhse',
            name='type_controle',
            field=models.CharField(choices=[('SANITAIRE', 'Sanitaire'), ('TECHNIQUE', 'Technique'), ('ELECTRIQUE', 'Electrique'), ('OCCUPATION', 'Occupation')], max_length=50),
        ),
    ]
