# Generated by Django 4.2.30 on 2026-08-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrain', '0002_plainte_date_limite_sla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionqhse',
            name='note_sanitaire',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
