# Generated by Django 4.2.30 on 2026-08-13 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patrimoine', '0004_local_photo_url'),
        ('terrain', '0003_inspectionqhse_note_sanitaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdreMission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=40, unique=True)),
                ('objet', models.CharField(max_length=255)),
                ('directives', models.TextField(blank=True)),
                ('type_controle', models.CharField(choices=[('SANITAIRE', 'Sanitaire'), ('TECHNIQUE', 'Technique'), ('ELECTRIQUE', 'Electrique'), ('OCCUPATION', 'Occupation')], max_length=50)),
                ('priorite', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYENNE', 'Moyenne'), ('ELEVEE', 'Elevée')], default='FAIBLE', max_length=50)),
                ('date_mission', models.DateTimeField()),
                ('statut', models.CharField(choices=[('EMIS', 'Emis'), ('EN_COURS', 'En cours'), ('EXECUTE', 'Exécuté'), ('ANNULE', 'Annulé')], default='EMIS', max_length=30)),
                ('compte_rendu', models.TextField(blank=True)),
                ('agent_assigne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordres_mission_recus', to=settings.AUTH_USER_MODEL)),
                ('emetteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordres_mission_emis', to=settings.AUTH_USER_MODEL)),
                ('inspection_resultat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordre_mission_origine', to='terrain.inspectionqhse')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordres_mission', to='patrimoine.local')),
                ('plainte_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordres_mission', to='terrain.plainte')),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterventionMaintenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('type_intervention', models.CharField(choices=[('PREVENTIVE', 'Préventive'), ('CURATIVE', 'Curative'), ('URGENCE', 'Urgence')], default='CURATIVE', max_length=30)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PLANIFIEE', max_length=30)),
                ('date_planifiee', models.DateTimeField()),
                ('date_realisation', models.DateTimeField(blank=True, null=True)),
                ('cout_estime', models.FloatField(blank=True, null=True)),
                ('cout_reel', models.FloatField(blank=True, null=True)),
                ('rapport', models.TextField(blank=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions_maintenance', to='patrimoine.local')),
                ('plainte_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions_maintenance', to='terrain.plainte')),
                ('technicien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interventions_maintenance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
    ]
