# Generated by Django 4.2.30 on 2026-08-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrain', '0004_ordremission_interventionmaintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plainte',
            name='photo_preuve',
            field=models.ImageField(blank=True, null=True, upload_to='plaintes_photos/'),
        ),
    ]
