# Generated by Django 4.2.30 on 2026-08-10 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0003_alter_utilisateur_role'),
        ('patrimoine', '0002_alter_local_options_rename_id_local_local_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppelCandidature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_lancement', models.DateTimeField()),
                ('date_cloture', models.DateTimeField()),
                ('est_actif', models.BooleanField(default=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appels_candidature', to='patrimoine.local')),
                ('publie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appels_publies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('type_demande', models.CharField(choices=[('RENOVATION', 'Rénovation'), ('CONSTRUCTION_CANDIDAT', 'Construction Candidat'), ('CONSTRUCTION_CROUST', 'Construction CROUS-T'), ('VENTE_PRODUIT', 'Vente de produit'), ('PRESTATION_SERVICE', 'Prestation de service'), ('LOCAL_ARTISANAL', 'Local artisanal')], max_length=32)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('MITIGEE_COMPLEMENT', 'Mitigée / Complément'), ('FAVORABLE', 'Favorable'), ('DEFAVORABLE', 'Défavorable')], default='EN_ATTENTE', max_length=32)),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('notes_admin', models.TextField(blank=True)),
                ('appel_candidature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures', to='demandes.appelcandidature')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='comptes.demandeur')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_directes', to='patrimoine.local')),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MembreCommission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_designation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_commission', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoteCommission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('avis', models.CharField(choices=[('FAVORABLE', 'Favorable'), ('DEFAVORABLE', 'Défavorable'), ('ABSTENTION', 'Abstention')], max_length=32)),
                ('commentaire', models.TextField(blank=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='demandes.demande')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_emis', to='demandes.membrecommission')),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoriqueStatutDemande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ancien_statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('MITIGEE_COMPLEMENT', 'Mitigée / Complément'), ('FAVORABLE', 'Favorable'), ('DEFAVORABLE', 'Défavorable')], max_length=32)),
                ('nouveau_statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('MITIGEE_COMPLEMENT', 'Mitigée / Complément'), ('FAVORABLE', 'Favorable'), ('DEFAVORABLE', 'Défavorable')], max_length=32)),
                ('commentaire_acteur', models.TextField(blank=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='demandes.demande')),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('pieces_recepissees', models.BooleanField(default=False)),
                ('est_complet', models.BooleanField(default=False)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to='demandes.demande')),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CritereAppel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('type_critere', models.CharField(choices=[('GENRE', 'Genre'), ('TRANCHE_AGE', "Tranche d'âge"), ('EXPERIENCE_PREALABLE', 'Expérience préalable'), ('AUTRE', 'Autre')], max_length=32)),
                ('valeur_cible', models.CharField(max_length=255)),
                ('poids', models.IntegerField(default=1)),
                ('actif', models.BooleanField(default=True)),
                ('appel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteres', to='demandes.appelcandidature')),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
    ]
