# Generated by Django 5.2.17 on 2026-08-10 20:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0002_remove_demandeur_nom_complet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppelCandidat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_lancement', models.DateTimeField()),
                ('date_cloture', models.DateTimeField()),
                ('description', models.TextField()),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('type_demande', models.CharField(choices=[('RENOVATION', 'Rénovation'), ('CONSTRUCTION_CANDIDAT', 'Construction candidat'), ('CONSTRUCTION_CROUST', 'Construction CROUS-T'), ('VENTE_ALIMENTAIRE', 'Vente alimentaire'), ('PRESTATION_SERVICE', 'Prestation de service'), ('LOCAL_ARTISANAL', 'Local artisanal')], max_length=30)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('MITIGEE_COMPLEMENT', 'Mitigée - complément requis'), ('FAVORABLE', 'Favorable'), ('DEFAVORABLE', 'Défavorable')], default='EN_ATTENTE', max_length=30)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='comptes.demandeur')),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('pieces_receptionnees', models.BooleanField(default=False)),
                ('est_complet', models.BooleanField(default=False)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to='demandes.demande')),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('type_document', models.CharField(choices=[('CARTE_ETUDIANT', 'Carte étudiant'), ('PIECE_IDENTITE', "Pièce d'identité"), ('REGISTRE_COMMERCE', 'Registre de commerce'), ('ATTESTATION_HYGIENE', "Attestation d'hygiène"), ('PLAN_AMENAGEMENT', "Plan d'aménagement"), ('AUTRE', 'Autre')], max_length=30)),
                ('nom_fichier', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='documents_demandes/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('est_valide', models.BooleanField(default=False)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='demandes.dossier')),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoriqueStatutDemande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('ancien_statut', models.CharField(blank=True, max_length=30, null=True)),
                ('nouveau_statut', models.CharField(max_length=30)),
                ('commentaire_acteur', models.TextField(blank=True, null=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques_demande', to=settings.AUTH_USER_MODEL)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='demandes.demande')),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
    ]
