# Generated by Django 4.2.30 on 2026-08-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='reference_anonyme',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
