# Generated by Django 4.2.30 on 2026-08-11 16:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0002_demande_reference_anonyme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dossier',
            old_name='pieces_recepissees',
            new_name='pieces_receptionnees',
        ),
        migrations.AlterField(
            model_name='demande',
            name='type_demande',
            field=models.CharField(choices=[('RENOVATION', 'Rénovation'), ('CONSTRUCTION_CANDIDAT', 'Construction Candidat'), ('CONSTRUCTION_CROUST', 'Construction CROUS-T'), ('VENTE_PRODUIT', 'Vente de produit'), ('VENTE_ALIMENTAIRE', 'Vente alimentaire'), ('PRESTATION_SERVICE', 'Prestation de service'), ('LOCAL_ARTISANAL', 'Local artisanal')], max_length=32),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('type_document', models.CharField(choices=[('CARTE_ETUDIANT', 'Carte étudiant'), ('PIECE_IDENTITE', "Pièce d'identité"), ('REGISTRE_COMMERCE', 'Registre de commerce'), ('ATTESTATION_HYGIENE', "Attestation d'hygiène"), ('PLAN_AMENAGEMENT', "Plan d'aménagement"), ('AUTRE', 'Autre')], max_length=30)),
                ('nom_fichier', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='documents_demandes/')),
                ('est_valide', models.BooleanField(default=False)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='demandes.dossier')),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
    ]
