# Generated by Django 4.2.30 on 2026-08-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0003_rename_pieces_recepissees_dossier_pieces_receptionnees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='statut',
            field=models.CharField(choices=[('NOUVELLE', 'Nouvelle demande'), ('CONTROLE_RECEVABILITE', 'Contrôle de recevabilité'), ('EN_ATTENTE_COMPLEMENT', 'En attente de compléments'), ('ETUDE_FAISABILITE', 'Étude de faisabilité'), ('CONTROLE_HYGIENE', 'Contrôle sanitaire et hygiène'), ('EN_ATTENTE_DECISION', 'En attente de décision finale'), ('FAVORABLE', 'Favorable'), ('DEFAVORABLE', 'Défavorable'), ('MITIGEE_ARCHIVEE', 'Mitigée (Archivée)'), ('EN_ATTENTE_SIGNATURE', 'En attente de signature')], default='NOUVELLE', max_length=32),
        ),
        migrations.AlterField(
            model_name='document',
            name='type_document',
            field=models.CharField(choices=[('CARTE_ETUDIANT', 'Carte étudiant'), ('PIECE_IDENTITE', "Pièce d'identité"), ('REGISTRE_COMMERCE', 'Registre de commerce'), ('ATTESTATION_HYGIENE', "Attestation d'hygiène"), ('PLAN_AMENAGEMENT', "Plan d'aménagement"), ('CV', 'Curriculum Vitae'), ('AUTORISATION_VENTE', 'Autorisation de vente'), ('BUSINESS_PLAN', 'Business Plan'), ('MAQUETTE_3D', 'Maquette 3D'), ('FICHE_SANTE', 'Fiche Santé Alimentaire'), ('AUTRE', 'Autre')], max_length=30),
        ),
        migrations.AlterField(
            model_name='historiquestatutdemande',
            name='ancien_statut',
            field=models.CharField(choices=[('NOUVELLE', 'Nouvelle demande'), ('CONTROLE_RECEVABILITE', 'Contrôle de recevabilité'), ('EN_ATTENTE_COMPLEMENT', 'En attente de compléments'), ('ETUDE_FAISABILITE', 'Étude de faisabilité'), ('CONTROLE_HYGIENE', 'Contrôle sanitaire et hygiène'), ('EN_ATTENTE_DECISION', 'En attente de décision finale'), ('FAVORABLE', 'Favorable'), ('DEFAVORABLE', 'Défavorable'), ('MITIGEE_ARCHIVEE', 'Mitigée (Archivée)'), ('EN_ATTENTE_SIGNATURE', 'En attente de signature')], max_length=32),
        ),
        migrations.AlterField(
            model_name='historiquestatutdemande',
            name='nouveau_statut',
            field=models.CharField(choices=[('NOUVELLE', 'Nouvelle demande'), ('CONTROLE_RECEVABILITE', 'Contrôle de recevabilité'), ('EN_ATTENTE_COMPLEMENT', 'En attente de compléments'), ('ETUDE_FAISABILITE', 'Étude de faisabilité'), ('CONTROLE_HYGIENE', 'Contrôle sanitaire et hygiène'), ('EN_ATTENTE_DECISION', 'En attente de décision finale'), ('FAVORABLE', 'Favorable'), ('DEFAVORABLE', 'Défavorable'), ('MITIGEE_ARCHIVEE', 'Mitigée (Archivée)'), ('EN_ATTENTE_SIGNATURE', 'En attente de signature')], max_length=32),
        ),
    ]
