# Generated by Django 4.2.30 on 2026-08-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0004_alter_demande_statut_alter_document_type_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='avis_sanitaire_externe',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='demande',
            name='reference_avis_sanitaire',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
