# Generated by Django 4.2.30 on 2026-08-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0005_demande_avis_sanitaire_externe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='description_projet',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='rdv_signature_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='demande',
            name='statut',
            field=models.CharField(choices=[('NOUVELLE', 'Nouvelle demande'), ('CONTROLE_RECEVABILITE', 'Contrôle de recevabilité'), ('MITIGEE_COMPLEMENT', 'En attente de compléments'), ('EN_EXPERTISE_TECHNIQUE', 'Expertise technique'), ('CONTROLE_HYGIENE', 'Contrôle sanitaire et hygiène'), ('EN_ATTENTE_DECISION', 'En attente de décision finale'), ('FAVORABLE', 'Favorable'), ('DEFAVORABLE', 'Défavorable'), ('MITIGEE_ARCHIVEE', 'Mitigée (Archivée)'), ('EN_ATTENTE_SIGNATURE', 'En attente de signature'), ('CONTRAT_ACCEPTE_RDV_FIXE', 'Contrat accepté (RDV fixé)'), ('CONTRAT_REFUSE', 'Contrat refusé')], default='NOUVELLE', max_length=32),
        ),
        migrations.AlterField(
            model_name='historiquestatutdemande',
            name='ancien_statut',
            field=models.CharField(choices=[('NOUVELLE', 'Nouvelle demande'), ('CONTROLE_RECEVABILITE', 'Contrôle de recevabilité'), ('MITIGEE_COMPLEMENT', 'En attente de compléments'), ('EN_EXPERTISE_TECHNIQUE', 'Expertise technique'), ('CONTROLE_HYGIENE', 'Contrôle sanitaire et hygiène'), ('EN_ATTENTE_DECISION', 'En attente de décision finale'), ('FAVORABLE', 'Favorable'), ('DEFAVORABLE', 'Défavorable'), ('MITIGEE_ARCHIVEE', 'Mitigée (Archivée)'), ('EN_ATTENTE_SIGNATURE', 'En attente de signature'), ('CONTRAT_ACCEPTE_RDV_FIXE', 'Contrat accepté (RDV fixé)'), ('CONTRAT_REFUSE', 'Contrat refusé')], max_length=32),
        ),
        migrations.AlterField(
            model_name='historiquestatutdemande',
            name='nouveau_statut',
            field=models.CharField(choices=[('NOUVELLE', 'Nouvelle demande'), ('CONTROLE_RECEVABILITE', 'Contrôle de recevabilité'), ('MITIGEE_COMPLEMENT', 'En attente de compléments'), ('EN_EXPERTISE_TECHNIQUE', 'Expertise technique'), ('CONTROLE_HYGIENE', 'Contrôle sanitaire et hygiène'), ('EN_ATTENTE_DECISION', 'En attente de décision finale'), ('FAVORABLE', 'Favorable'), ('DEFAVORABLE', 'Défavorable'), ('MITIGEE_ARCHIVEE', 'Mitigée (Archivée)'), ('EN_ATTENTE_SIGNATURE', 'En attente de signature'), ('CONTRAT_ACCEPTE_RDV_FIXE', 'Contrat accepté (RDV fixé)'), ('CONTRAT_REFUSE', 'Contrat refusé')], max_length=32),
        ),
    ]
