# Generated by Django 4.2.30 on 2026-08-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0006_demande_description_projet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='avis_technique_interne',
            field=models.TextField(blank=True),
        ),
    ]
