# Generated by Django 4.2.30 on 2026-08-14 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demandes', '0010_archivage_commission_routage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'verbose_name': "Commission d'évaluation", 'verbose_name_plural': "Commissions d'évaluation"},
        ),
        migrations.AddField(
            model_name='demande',
            name='partage_avec',
            field=models.ManyToManyField(blank=True, related_name='demandes_partagees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commission',
            name='delegation_directeur',
            field=models.BooleanField(default=False, help_text='Si actif, la commission peut prendre les decisions du Directeur CROUS-T.'),
        ),
    ]
