# Generated by Django 4.2.30 on 2026-08-15 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patrimoine', '0007_remove_local_capacite_accueil'),
        ('demandes', '0011_alter_commission_options_demande_partage_avec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='statut',
            field=models.CharField(choices=[('NOUVELLE', 'Nouvelle demande'), ('CONTROLE_RECEVABILITE', 'Contrôle de recevabilité'), ('MITIGEE_COMPLEMENT', 'En attente de compléments'), ('EN_EXPERTISE_TECHNIQUE', 'Expertise technique'), ('CONTROLE_HYGIENE', 'Contrôle sanitaire et hygiène'), ('EN_ATTENTE_DECISION', 'En attente de décision finale'), ('EN_COMMISSION', "Transmis à la Commission d'évaluation"), ('FAVORABLE', 'Favorable'), ('DEFAVORABLE', 'Défavorable'), ('MITIGEE_ARCHIVEE', 'Mitigée (Archivée)'), ('EN_ATTENTE_SIGNATURE', 'En attente de signature'), ('CONTRAT_ACCEPTE_RDV_FIXE', 'Contrat accepté (RDV fixé)'), ('CONTRAT_REFUSE', 'Contrat refusé')], default='NOUVELLE', max_length=32),
        ),
        migrations.AlterField(
            model_name='historiquestatutdemande',
            name='ancien_statut',
            field=models.CharField(choices=[('NOUVELLE', 'Nouvelle demande'), ('CONTROLE_RECEVABILITE', 'Contrôle de recevabilité'), ('MITIGEE_COMPLEMENT', 'En attente de compléments'), ('EN_EXPERTISE_TECHNIQUE', 'Expertise technique'), ('CONTROLE_HYGIENE', 'Contrôle sanitaire et hygiène'), ('EN_ATTENTE_DECISION', 'En attente de décision finale'), ('EN_COMMISSION', "Transmis à la Commission d'évaluation"), ('FAVORABLE', 'Favorable'), ('DEFAVORABLE', 'Défavorable'), ('MITIGEE_ARCHIVEE', 'Mitigée (Archivée)'), ('EN_ATTENTE_SIGNATURE', 'En attente de signature'), ('CONTRAT_ACCEPTE_RDV_FIXE', 'Contrat accepté (RDV fixé)'), ('CONTRAT_REFUSE', 'Contrat refusé')], max_length=32),
        ),
        migrations.AlterField(
            model_name='historiquestatutdemande',
            name='nouveau_statut',
            field=models.CharField(choices=[('NOUVELLE', 'Nouvelle demande'), ('CONTROLE_RECEVABILITE', 'Contrôle de recevabilité'), ('MITIGEE_COMPLEMENT', 'En attente de compléments'), ('EN_EXPERTISE_TECHNIQUE', 'Expertise technique'), ('CONTROLE_HYGIENE', 'Contrôle sanitaire et hygiène'), ('EN_ATTENTE_DECISION', 'En attente de décision finale'), ('EN_COMMISSION', "Transmis à la Commission d'évaluation"), ('FAVORABLE', 'Favorable'), ('DEFAVORABLE', 'Défavorable'), ('MITIGEE_ARCHIVEE', 'Mitigée (Archivée)'), ('EN_ATTENTE_SIGNATURE', 'En attente de signature'), ('CONTRAT_ACCEPTE_RDV_FIXE', 'Contrat accepté (RDV fixé)'), ('CONTRAT_REFUSE', 'Contrat refusé')], max_length=32),
        ),
        migrations.CreateModel(
            name='LotCommission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('commentaire', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('EN_COURS', "En cours d'évaluation"), ('CLOTURE', 'Clôturé')], default='EN_COURS', max_length=20)),
                ('commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='demandes.commission')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_crees', to=settings.AUTH_USER_MODEL)),
                ('demandes', models.ManyToManyField(related_name='lots_commission', to='demandes.demande')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots_commission', to='patrimoine.local')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
