# Generated by Django 6.1 on 2026-08-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0012_alter_demande_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='statut',
            field=models.CharField(choices=[('NOUVELLE', 'En attente'), ('CONTROLE_RECEVABILITE', 'Contrôle de recevabilité'), ('MITIGEE_COMPLEMENT', 'En attente de compléments'), ('EN_EXPERTISE_TECHNIQUE', 'Expertise technique'), ('CONTROLE_HYGIENE', 'Contrôle sanitaire et hygiène'), ('EN_ATTENTE_DECISION', 'En attente de décision finale'), ('EN_COMMISSION', "Transmis à la Commission d'évaluation"), ('FAVORABLE', 'Favorable'), ('DEFAVORABLE', 'Défavorable'), ('MITIGEE_ARCHIVEE', 'Mitigée (Archivée)'), ('EN_ATTENTE_SIGNATURE', 'En attente de signature'), ('CONTRAT_ACCEPTE_RDV_FIXE', 'Contrat accepté (RDV fixé)'), ('CONTRAT_REFUSE', 'Contrat refusé')], default='NOUVELLE', max_length=32),
        ),
        migrations.AlterField(
            model_name='historiquestatutdemande',
            name='ancien_statut',
            field=models.CharField(choices=[('NOUVELLE', 'En attente'), ('CONTROLE_RECEVABILITE', 'Contrôle de recevabilité'), ('MITIGEE_COMPLEMENT', 'En attente de compléments'), ('EN_EXPERTISE_TECHNIQUE', 'Expertise technique'), ('CONTROLE_HYGIENE', 'Contrôle sanitaire et hygiène'), ('EN_ATTENTE_DECISION', 'En attente de décision finale'), ('EN_COMMISSION', "Transmis à la Commission d'évaluation"), ('FAVORABLE', 'Favorable'), ('DEFAVORABLE', 'Défavorable'), ('MITIGEE_ARCHIVEE', 'Mitigée (Archivée)'), ('EN_ATTENTE_SIGNATURE', 'En attente de signature'), ('CONTRAT_ACCEPTE_RDV_FIXE', 'Contrat accepté (RDV fixé)'), ('CONTRAT_REFUSE', 'Contrat refusé')], max_length=32),
        ),
        migrations.AlterField(
            model_name='historiquestatutdemande',
            name='nouveau_statut',
            field=models.CharField(choices=[('NOUVELLE', 'En attente'), ('CONTROLE_RECEVABILITE', 'Contrôle de recevabilité'), ('MITIGEE_COMPLEMENT', 'En attente de compléments'), ('EN_EXPERTISE_TECHNIQUE', 'Expertise technique'), ('CONTROLE_HYGIENE', 'Contrôle sanitaire et hygiène'), ('EN_ATTENTE_DECISION', 'En attente de décision finale'), ('EN_COMMISSION', "Transmis à la Commission d'évaluation"), ('FAVORABLE', 'Favorable'), ('DEFAVORABLE', 'Défavorable'), ('MITIGEE_ARCHIVEE', 'Mitigée (Archivée)'), ('EN_ATTENTE_SIGNATURE', 'En attente de signature'), ('CONTRAT_ACCEPTE_RDV_FIXE', 'Contrat accepté (RDV fixé)'), ('CONTRAT_REFUSE', 'Contrat refusé')], max_length=32),
        ),
    ]
