# Generated by Django 4.2.30 on 2026-08-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0013_alter_demande_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appelcandidature',
            name='loyer_mensuel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant du loyer ou redevance mensuelle en FCFA', max_digits=12),
        ),
    ]
