# Generated by Django 4.2.30 on 2026-08-10 19:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0003_alter_utilisateur_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('points_modifies', models.FloatField()),
                ('nouveau_score', models.FloatField()),
                ('motif', models.CharField(max_length=255)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_score', to='comptes.demandeur')),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
    ]
