# Generated by Django 4.2.30 on 2026-08-12 04:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateField(auto_now_add=True)),
                ('pin', models.CharField(choices=[('pin-navy', 'Bleu Marine (Navy)'), ('pin-slate', 'Gris (Slate)'), ('pin-gold', 'Or (Gold)')], default='pin-navy', max_length=20)),
                ('bg', models.CharField(default='#fffde7', help_text='Couleur de fond hexadécimale', max_length=20)),
                ('est_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date_publication', '-date_creation'],
            },
        ),
    ]
