# Generated by Django 4.2.30 on 2026-08-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parametresysteme'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='consigne_direction',
            field=models.TextField(blank=True, default='', help_text='Consignes de diffusion de la Direction'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='emetteur_nom',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='annonce',
            name='statut',
            field=models.CharField(choices=[('A_PUBLIER', 'À publier (Demande Direction)'), ('PUBLIEE', 'Publiée'), ('ARCHIVEE', 'Archivée')], default='PUBLIEE', max_length=30),
        ),
    ]
