# Generated by Django 4.2.30 on 2026-08-10 18:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Echeance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_exigibilite', models.DateField()),
                ('montant_du', models.FloatField()),
                ('montant_penalite', models.FloatField(default=0.0)),
                ('statut', models.CharField(choices=[('NON_ECHUE', 'Non échue'), ('EXIGIBLE', 'Exigible'), ('PAYEE', 'Payée'), ('EN_RETARD', 'En retard')], default='NON_ECHUE', max_length=20)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='contrats.contrat')),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('montant_regle', models.FloatField()),
                ('mode', models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('ESPECES', 'Espèces')], max_length=20)),
                ('reference_transaction', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('reference_quitus', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('echeance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='paiements.echeance')),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
    ]
