# Generated by Django 4.2.30 on 2026-08-10 19:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='MOBILE_MONEY', max_length=50)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=255)),
                ('payload_brut', models.TextField(blank=True, help_text='Données brutes reçues du webhook')),
                ('statut_api', models.CharField(blank=True, max_length=50)),
                ('erreur', models.TextField(blank=True)),
                ('paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='paiements.paiement')),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
    ]
