# Generated by Django 4.2.30 on 2026-08-13 01:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0002_transactionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReversementAmicale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('montant_reverse', models.FloatField()),
                ('date_reversement', models.DateTimeField(auto_now_add=True)),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reversement', to='paiements.paiement')),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
    ]
