export const ROLES = {
  USAGER: "USAGER",
  BUREAU_COURRIER: "BUREAU_COURRIER",
  AGENT_DCUVE: "AGENT_DCUVE",
  DIRECTEUR_DCUVE: "DIRECTEUR_DCUVE",
  DIRECTEUR_CROUS_T: "DIRECTEUR_CROUS_T",
  SERVICE_JURIDIQUE: "SERVICE_JURIDIQUE",
  SERVICE_COMPTABLE: "SERVICE_COMPTABLE",
  SERVICE_TECHNIQUE: "SERVICE_TECHNIQUE",
  AGENT_TERRAIN: "AGENT_TERRAIN",
  AGENT_QHSE: "AGENT_QHSE",
  CELLULE_COMMUNICATION: "CELLULE_COMMUNICATION",
  AMICALE: "AMICALE",
  ADMINISTRATEUR_SI: "ADMINISTRATEUR_SI",
};

export const STATUTS_DEMANDE = {
  EN_ATTENTE: "EN_ATTENTE",
  MITIGEE_COMPLEMENT: "MITIGEE_COMPLEMENT",
  FAVORABLE: "FAVORABLE",
  DEFAVORABLE: "DEFAVORABLE",
};

export const TYPES_LOCAL = {
  RESTAURATION: "RESTAURATION",
  MULTISERVICES: "MULTISERVICES",
  PAPETERIE: "PAPETERIE",
  ARTISANAT: "ARTISANAT",
  AUTRE: "AUTRE",
};
