# Generated by Django 4.2.30 on 2026-08-10 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comptes', '0003_alter_utilisateur_role'),
        ('patrimoine', '0002_alter_local_options_rename_id_local_local_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_signature', models.DateField(default=django.utils.timezone.now)),
                ('date_debut', models.DateField()),
                ('duree_mois', models.PositiveIntegerField(default=24)),
                ('preavis_mois', models.PositiveIntegerField(default=3)),
                ('redevance_mensuelle', models.FloatField()),
                ('montant_caution', models.FloatField()),
                ('est_gratuit', models.BooleanField(default=False)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_resiliation', models.DateField(blank=True, null=True)),
                ('motif_resiliation', models.TextField(blank=True, null=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats_titulaire', to='comptes.demandeur')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='patrimoine.local')),
                ('signataire_crous_t', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats_signes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
    ]
