# Generated by Django 4.2.30 on 2026-08-11 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0005_demande_avis_sanitaire_externe_and_more'),
        ('contrats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='demande',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demandes.demande'),
        ),
    ]
