# Generated by Django 4.2.30 on 2026-08-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0003_phase4_juridique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrat',
            name='montant_caution',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='redevance_mensuelle',
        ),
    ]
