# Generated by Django 4.2.30 on 2026-08-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0004_remove_contrat_montant_caution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='convocation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='convocation_envoyee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contrat',
            name='convocation_lieu',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contrat',
            name='convocation_mode',
            field=models.CharField(choices=[('PHYSIQUE', 'Physique'), ('VIRTUELLE', 'Virtuelle')], default='PHYSIQUE', max_length=20),
        ),
    ]
